linters-settings:
  gocyclo:
    min-complexity: 25
  govet:
    check-shadowing: false
  misspell:
    locale: "US"

linters:
  enable-all: true
  disable:
    - stylecheck
    - gosec
    - dupl
    - maligned
    - depguard
    - lll
    - prealloc
    - scopelint
    - gocritic
    - gochecknoinits
    - gochecknoglobals
    - godox
    - funlen
    - wsl
    - whitespace
    - gomnd

issues:
  exclude-use-default: true
  max-per-linter: 0
  max-same-issues: 0
  # The following excludes are considered false-positives/known-OK.
  exclude-rules:
    - path: ca([/|\\])ca.go
      text: 'type name will be used as ca.CAImpl by other packages, and that stutters; consider calling this Impl'
    - path: va([/|\\])va.go
      text: 'type name will be used as va.VAImpl by other packages, and that stutters; consider calling this Impl'
    - path: wfe([/|\\])wfe.go
      text: 'if` block ends with a `return` statement, so drop this `else` and outdent its block'
